### ISSUE TITLE
Improving ZimSearch

### ISSUE THREAD

**Issue by sojusnik** [dsboger/zimsearch#1]
Hey Davi,

I had a look on the install.sh and found out, that

```
# plugin file
install -D -m644 gnomeshellsearch.py "${rootdir}/usr/lib/python2.7/site-packages/zim/plugins/gnomeshellsearch.py"
```

was the cause. After manually copying `gnomeshellsearch.py` to `/home/sojusnik/.local/share/zim/plugins/gnomeshellsearch.py` your plugin finally worked!

Would it be possible to adapt your install script in a further release, so that it will run OOTB with Ubuntu Gnome?

When using your plugin, I've realized that it takes some time for the results to show up in the Gnome Shell Overview. Do you thought about speeding this process up? ATM, it takes about 6 to 7 seconds to show up, whereas search results from nautilus and other plugins appear nearly instantly.

One way to speed this process up is to use Strg+J (go to page) instead of Strg+Shift+F (search all notes) in your plugin. I think that the delay is caused by the search process, the Strg+J results however should appear nearly instantly, because the Zim pages are already indexed, so that there shouldn't be any search delay. Additionally, the Strg+Shift+F is a little bit over the top for the Gnome Shell Overview, since you want to open a certain Zim page and not perform a search through the whole notebook.

What do you think?

Best wishes!

**Comment by dsboger-zz** [comment]
Hello sojusnik,

thanks for the feedback and sorry for the delay.

I committed some tentative autotools infrastructure trying to solve build problems. I also sketched some installation instructions in INSTALL. As before, I tested everything in my ArchLinux box using the AUR package I maintain (zimsearch-git). I suppose it should work on most systems.

With respect to the search strategy, currently I use basically the same as calling zim --search from command line. That is a full-text search, so that is why it takes that long to show results. It definitely makes much more sense to do title-only search, so I'll investigate how to do that next.

**Comment by dsboger-zz** [comment]
I pushed a commit changing the search strategy. Now it walks the notebook index and matches the whole query against the page titles (not the full path). The search is still not fully asynchronous, so it may still not be perfectly responsible for very large notebooks. I'm planning for further improvements like matching terms out of order, but for now I'll close this issue.

**Comment by sojusnik** [comment]
Thanks!
I'll have a look asap.
