### ISSUE TITLE
Compatibilty with Zim 0.67-rc2

### ISSUE THREAD

**Issue by sojusnik** [dsboger/zimsearch#11]
It seems, that Zimsearch is currently not compatible with the [0.67-rc2](https://github.com/jaap-karssenberg/zim-desktop-wiki/releases) version of Zim, that was released recently.

I've followed your instructions, the installation process went well, but don't received any results in the Gnome-Shell. Of course I've enabled both the Gnome-Shell search plugin and the Zim one. Restarted, but without any effect. Happens with Ubuntu Gnome 17.04.

All files seem to be on their place:
```
$ find /usr -iname '*zim*search*' -ls
  5773136      4 -rwxr-xr-x   1 root     root          444 Jun 15 19:38 /usr/local/bin/zim-gnomeshellsearch
  5799999      4 drwxr-sr-x   2 root     staff        4096 Jun 15 19:38 /usr/local/lib/python2.7/dist-packages/zimsearch-0.0.1.egg-info
  5773131      4 -rw-r--r--   1 root     root          180 Jun 15 19:38 /usr/local/share/gnome-shell/search-providers/zim.plugins.gnomeshellsearch.provider.ini
  5773130      4 -rw-r--r--   1 root     root          114 Jun 15 19:38 /usr/local/share/dbus-1/services/zim.plugins.gnomeshellsearch.provider.service
  5799972      4 drwxr-xr-x   5 root     root         4096 Jun 15 19:38 /usr/local/src/zimsearch
  5773124      4 -rw-r--r--   1 root     root          121 Jun 15 19:38 /usr/local/src/zimsearch/data/zim.plugins.gnomeshellsearch.provider.service.in
  5773123      4 -rw-r--r--   1 root     root          180 Jun 15 19:38 /usr/local/src/zimsearch/data/zim.plugins.gnomeshellsearch.provider.ini.in
  5773128      4 -rwxr-xr-x   1 root     root          449 Jun 15 19:38 /usr/local/src/zimsearch/zim-gnomeshellsearch
```

**Comment by sojusnik** [comment]
Today the [stable v0.67](https://github.com/jaap-karssenberg/zim-desktop-wiki/releases) was released. Here's the [changelog](https://github.com/jaap-karssenberg/zim-desktop-wiki/blob/master/CHANGELOG.txt).

Would be great to finally have Zimsearch working with the latest Zim release.

**Comment by achadwick** [comment]
Confirmed as broken as of zim-desktop-wiki 2d0ead5a9736267766dfa669f2e78d27a2a5c110 thru tag 0.67. I've been playing around with zimsearch trying to fix up searches (using the approved zim.seach interface, no less), but invoking the result is proving harder.

Working on it.

**Comment by sojusnik** [comment]
How is it progressing? I'm really missing your great plugin for the latest Zim version. Wishing you good luck!

**Comment by sojusnik** [comment]
Without your great plugin using Zim on Gnome just doesn't feel right :) Please let me know, if I somehow can help you in adapting your plugin to the newest Zim version. I'm coding illiterate, but maybe could help you otherwise. For instance, this [guy](https://github.com/DerPferd/external) recently released a [Zim plugin](https://github.com/DerPferd/external/blob/d6e5fc0c875d39eab870d04e905a223d820b79c6/org.albert.extension.external.zim.py) ([comments](https://github.com/albertlauncher/external/pull/4)) for [Albert](https://github.com/albertlauncher/albert). Maybe it could help you to solve your problem.

Best wishes!

**Comment by achadwick** [comment]
That should fix things for 0.67 :smile: 

* The plugin now uses Zim's external API to find notebooks, and uses it for searching too.
* This means it's not just page title hits any more (let me know if there are problems with that!)
* Zim can't be pointed at a page using the old IPC mechanism any more, meaning the plugin now runs zim directly in a detached process to activate a result.
* Means clicking on the icon to the left of the results now does something else (it's supposed to launch zim with your search results, but since that can't be done you now see a list of notebooks)
* This means that the D-Bus core of zimsearch could be rewritten as a conventional Python-GI GApplication now. I'd be down with that, no more PyGTK-era gtk.main() nastiness!

Sorry this has taken so long to fix. Thanks again for the report.

**Comment by sojusnik** [comment]
Huge thanks!!

> This means it's not just page title hits any more (let me know if there are problems with that!)

Although I have a quite fast PC, the new approach feels very sluggish to me. It takes about 5 seconds for the results to appear. At the beginning I even thought, that this plugin doesn't work at all, because the previous versions showed the results instantly. Only by accident I saw the new results, when the Gnome-Shell stayed open a little longer than usual. IMHO, the current approach is too slow to have a practical value.

Additionally, the current search results aren't sorted according to their weight/frequency, as done in Zim, when using "search in notebook" or "go/jump to page".

I really think, that it's absolutely sufficient to search only for the page title, not the content itself, like it was before. In that case you would significantly speed up the searching process. In case of need, I also can imagine separating the results for the page titles and the content. So the page results should be at the beginning and if there is still place left, then content results could be shown. But I think, that the creator of Zim had a very good reason to separate both searching methods and your great plugin should also do it that way.

I'm looking forward to your answer.

**Comment by achadwick** [comment]
Sound like lots of separate issues. Mind raising them as separate issues so they can be worked on separately?

Slight confession: I've been using Xfce and Kupfer recently, since Debian testing/unstable broke GNOME in a few places that matter to me. It'd be nice to get Kupfer talking to D-Bus SearchProvider2 services - I wonder if anyone's done that yet?  That'd give me an impetus to work on the new speed issues.

**Comment by sojusnik** [comment]
Sorry for the delay. I've opened [this](https://github.com/achadwick/zimsearch/issues/13) and [this](https://github.com/achadwick/zimsearch/issues/14) issue.
