### ISSUE TITLE
Help on Debian 9 

### ISSUE THREAD

**Issue by lyndhurst** [dsboger/zimsearch#12]
I just found out about this plugin as I switched to Gnome from Xfce a week ago. 
If I can make it work, this would be one of the greatest addition to my setup so far; so I really hope you can help!
I tried installing with the two ways you described (with and without "--system" in the command), and of course, I did try logging in and out, even restarting.
In both cases, 

- I have a successful install message from terminal,
-  Gnome shell search appears in the zim plugin list, and I can enable it.
-  There is an entry "Zim Desktop Wiki" in Gnome System/Settings/Search list, it is enabled.

Unfortunately, when I click on "Activities" the search does not show any results from Zim pages.

There is one thing I am not sure of, after popping the "Activities" overview panel should I press the "Meta" key, and then my search string, or, do you refer to this "meta" key as the keyboard shortcut to switch to the overview panel?
I anyway tried disabling the keyboard shortcut so that the "meta" key does not toggle the overview panel off to see if some Zim search would show up with no success.

For information, I am on Debian 9 stable, Gnome 3.22 and Zim 0.65 installed through apt.
So I am wondering if I am missing something here, but I do not know how to debug or investigate further,  I would really appreciate any help.
Thank you for your time.

**Comment by achadwick** [comment]
You need to be using Zim 0.67 for the latest master of zimsearch. Things have changed internally in Zim, and the head is not tested on Zim 0.65.

Zim 0.67 is not available in backports. It can be installed from https://github.com/jaap-karssenberg/zim-desktop-wiki, and contains Debian build stuff

    # apt-get install build-essential developers-reference
    # apt-get build-dep zim    # start with what zim 0.65 builds with
    
    $ fakeroot debian/rules binary     # then install the .deb as root

Alternatively, you may be able to use zimsearch at revision 7da6e72db48e03580d2e2b82daaa7c0459fdedbf with older Zim (`git co 7da6e72d`).

BTW, I switched to Xfce from Gnome a while back, since it broke things in Debian testing...

> There is one thing I am not sure of, after popping the "Activities" overview panel should I press the "Meta" key, and then my search string, or, do you refer to this "meta" key as the keyboard shortcut to switch to the overview panel?

No. <kbd>Meta</kbd> represents the normal way of showing the Activities overviiew. You can click on the Activities button in the top left corner to start searching too, but why use a touchscreen/mouse/touchpad when you don't have to?

The <kbd>Meta</kbd> key often has a Windows symbol on it.

> I anyway tried disabling the keyboard shortcut so that the "meta" key does not toggle the overview panel off to see if some Zim search would show up with no success.

There is no need for this. You can click/press on "Activities" too. If you are not using an English-language desktop, it may be labelled something else.
